spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/springVue
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

custom:
  clientId: clientApp
  clientSecret: secret
  jwtKey: test

---

spring.profiles: real1
spring.profiles.include: real-db

server:
  port: 8081

custom:
  clientId: clientApp
  clientSecret: secret
  jwtKey: test

---

spring.profiles: real2
spring.profiles.include: real-db

server:
  port: 8082

custom:
  clientId: clientApp
  clientSecret: secret
  jwtKey: test

